import { TimelineEventData } from "./types";

// 화면 검증용 예시 데이터. mockSegments와 태그를 겹치게 설계해서
// "그물망 연결"(links, link_basis=인물/장소/사건)이 실제로 있을 때
// 연표 화면에서 구술·사료가 어떻게 교차해 보여야 하는지 확인한다.
// 연표 도메인이 1900–2026이므로 세기 전체에 사건을 흩어 놓았다.
// 좌표는 가상의 지역이라 임의값(한국 중부권 근방)이다.

export const mockTimelineEvents: TimelineEventData[] = [
  {
    id: "evt-101",
    eventName: "경부선 OO역 영업 개시",
    dateValue: "1905-01",
    summary: "경부선 개통과 함께 OO역이 영업을 시작했다. 역 앞으로 시가지가 형성되는 출발점이 된다.",
    sourceReference: "철도청 역사(驛史) 편람",
    places: [{ name: "OO역", lat: 36.62, lng: 127.49 }],
    keywordTags: ["철도", "OO군"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "rel-101",
        type: "사진",
        title: "OO역 준공 기념사진",
        sourceOrg: "철도박물관",
        sourceUrl: "https://example.org/archive/photo/rel-101",
        description: "역사(驛舍) 앞에 관계자들이 모여 찍은 준공 기념사진.",
      },
    ],
  },
  {
    id: "evt-102",
    eventName: "OO장터 만세운동",
    dateValue: "1919-04-01",
    summary: "장날에 모인 군중이 만세를 불렀다. 주동자 수십 명이 검거되었다.",
    sourceReference: "삼일운동DB(국사편찬위원회)",
    places: [{ name: "OO장터", lat: 36.6, lng: 127.47 }],
    keywordTags: ["삼일운동", "OO군"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "evt-001",
    eventName: "OO면 피난민 수용 시작",
    dateValue: "1950-12",
    summary: "1·4 후퇴를 앞두고 남하한 피난민들이 OO면 일대에 집단 수용되었다. 임시 천막촌이 형성되었다.",
    sourceReference: "OO도 도지(道誌), 1985",
    places: [{ name: "OO면 피난촌", lat: 36.55, lng: 127.52 }],
    keywordTags: ["한국전쟁", "피난", "OO군"],
    linkedSegmentIds: ["seg-003"],
    linkedMaterials: [
      {
        id: "rel-006",
        type: "지도",
        title: "1951년 OO면 행정구역도",
        sourceOrg: "한국학자료센터",
        sourceUrl: "https://example.org/archive/map/rel-006",
        description: "전쟁 직후 OO면 일대의 행정구역을 표시한 고지도.",
      },
    ],
  },
  {
    id: "evt-002",
    eventName: "중앙시장 정식 개장",
    dateValue: "1962",
    summary: "노점과 좌판이 모여 있던 자리에 상설 점포가 들어서며 중앙시장이 정식 개장했다.",
    sourceReference: "OO시사(市史), 1994",
    places: [{ name: "중앙시장", lat: 36.63, lng: 127.48 }],
    keywordTags: ["시장", "도시화", "OO시"],
    linkedSegmentIds: ["seg-001"],
    linkedMaterials: [
      {
        id: "rel-001",
        type: "사진",
        title: "중앙시장 새벽 풍경",
        sourceOrg: "지역문화원 사진자료실",
        sourceUrl: "https://example.org/archive/photo/rel-001",
        description: "1970년대 후반 중앙시장 개장 직전 풍경을 담은 흑백 사진.",
      },
    ],
  },
  {
    id: "evt-003",
    eventName: "OO면 행정구역 개편",
    dateValue: "1963",
    summary: "군 경계 조정에 따라 OO면의 일부 리(里)가 인접 면으로 편입되었다.",
    sourceReference: "행정구역 연혁집",
    places: [{ name: "OO면 피난촌", lat: 36.55, lng: 127.52 }],
    keywordTags: ["행정", "OO군"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "evt-004",
    eventName: "OO공단 1차 준공",
    dateValue: "1974",
    summary: "수출 산업 육성 정책에 따라 OO공단 1차 부지가 준공되었다. 섬유·전자 업종이 먼저 입주했다.",
    sourceReference: "OO공단 30년사",
    places: [{ name: "OO공단", lat: 36.58, lng: 127.55 }],
    keywordTags: ["산업화", "OO시"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "rel-104",
        type: "사진",
        title: "OO공단 1차 부지 준공식",
        sourceOrg: "국가기록원",
        sourceUrl: "https://example.org/archive/photo/rel-104",
        description: "부지 준공식 현장을 촬영한 사진. 초기 입주 공장 건물이 함께 찍혀 있다.",
      },
    ],
  },
  {
    id: "evt-005",
    eventName: "OO공단 입주기업 대거 유치",
    dateValue: "1983",
    summary: "2차 확장 부지가 조성되며 입주기업이 크게 늘었다. 인근 농촌에서 젊은 노동력이 대거 유입된 시기다.",
    sourceReference: "공단 입주기업 명부",
    places: [{ name: "OO공단", lat: 36.58, lng: 127.55 }],
    keywordTags: ["노동사", "산업화", "OO시"],
    linkedSegmentIds: ["seg-002"],
    linkedMaterials: [
      {
        id: "rel-005",
        type: "사진",
        title: "OO공단 입주기업 명부 표지",
        sourceOrg: "국가기록원",
        sourceUrl: "https://example.org/archive/photo/rel-005",
        description: "1983년 3월 작성된 입주기업 명부 표지.",
      },
      {
        id: "rel-003",
        type: "논문",
        title: "「1980년대 지방 공단 노동력 이동 연구」",
        sourceOrg: "OO대학교 논문 저장소",
        sourceUrl: "https://example.org/archive/paper/rel-003",
        description: "지방 산업단지 초기 노동력 유입 경로를 다룬 연구 논문.",
      },
    ],
  },
  {
    id: "evt-006",
    eventName: "중앙시장 화재로 일부 소실",
    dateValue: "1988-09",
    summary: "포목전 구역에서 시작된 불로 점포 40여 곳이 소실되었다. 이듬해 상가 재건축의 계기가 된다.",
    sourceReference: "OO일보 縮刷版",
    places: [{ name: "중앙시장", lat: 36.63, lng: 127.48 }],
    keywordTags: ["시장", "OO시"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "rel-106",
        type: "사진",
        title: "화재 이튿날 중앙시장 포목전 구역",
        sourceOrg: "OO일보 사진자료실",
        sourceUrl: "https://example.org/archive/photo/rel-106",
        description: "불에 탄 점포와 잔해를 정리하는 상인들의 모습.",
      },
    ],
  },
  {
    id: "evt-103",
    eventName: "중앙시장 상가 현대화 사업",
    dateValue: "2004",
    summary: "아케이드 설치와 점포 정비가 이뤄졌다. 옛 포목전 골목의 흔적이 이때 대부분 사라졌다.",
    sourceReference: "OO시 도시재생 백서",
    places: [{ name: "중앙시장", lat: 36.63, lng: 127.48 }],
    keywordTags: ["시장", "도시재생", "OO시"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "evt-104",
    eventName: "OO시 구술채록 사업 시작",
    dateValue: "2019",
    summary: "시 문화재단이 원로 시민 구술채록을 시작했다. 이 아카이브가 다루는 구술 자료의 상당수가 이 사업의 산출물이다.",
    sourceReference: "OO문화재단 연차보고서",
    places: [{ name: "OO시", lat: 36.64, lng: 127.49 }],
    keywordTags: ["구술채록", "생애사", "OO시"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
];
