import { SegmentCardData, TimelineEventData, Utterance } from "./types";

// fragments_index 구글 시트(chronicle · oral segments 탭)에서 옮겨온 실데이터.
// - 사건명/날짜/출처ID/키워드/구술 전문은 시트 그대로.
// - 시트에서 비어 있는 부분은 목업으로 채웠다:
//   · summary(내용) — content 컬럼이 전부 비어 있어 사건명을 풀어쓴 한 줄 설명(임시)
//   · linkedSegmentIds — 시트의 event_id 컬럼이 비어 있어 주제가 겹치는 구술을 임시로 연결
//   · linkedMaterials — 10건은 국가기록원 OpenAPI(searcharc)로 검색해 실제 기록물 메타데이터·링크를
//     연결했다(scripts/match-archives.mjs, 6-5 정책대로 원문은 저장하지 않고 메타데이터+링크만).
//     검색으로 신뢰할 만한 결과가 없었던 나머지는 placeholder(example.org)로 남겨둠.
//   · 구술 제목 — item_title 컬럼이 비어 있어 persons_authority의 "이름(출생연도)" + 페이지로 구성
// - 인물(P···)은 화면에 ID 그대로 노출하지 않는다 — narrator_id/interviewer_id는 사람이 읽을 이름이
//   아니라 내부 참조 키라 그대로 보이면 의미 없는 값이 됨. persons_authority에서 이름·출생연도를
//   가져와 "이름(출생연도)" 형태로만 표기한다 (구술자만 — 면담자는 화면에 노출하지 않는 기존 방침 유지).
// - 출처(SRC···)는 sources_authority 탭의 title·url을 그대로 가져와 "본 구술 자료로 연결되는 링크"로 쓴다.
//   url이 없는 출처(예: 백과 항목)는 링크 대신 제목만 표시.
// - E026~E120(95건)은 data.go.kr의 "교육부 국사편찬위원회_우리역사넷 정보_오늘의역사(연표)" 원문파일
//   (data/raw/th.xml, 사용자가 직접 업로드)에서 라디오·방송 관련 사건만 걸러 추가한 것.
//   이 자료는 날짜+제목만 있고 본문이 따로 없어 summary는 eventName과 동일하다(내용 날조 아님, 원자료 그대로).
//   기존 25건과 겹치는 사건 중 날짜가 더 정밀하거나 다른 경우(E003·E004·E012·E016·E024)는 이 자료로
//   보정하고 sourceReference에 근거를 병기했다 — E016은 SRC007(9/3)과 국사편찬위원회(10/2)가 서로 다른
//   날짜를 기록한 이견(discrepancy) 사례라 summary에 그대로 남겨뒀다(6-4 원칙: 판단하지 않고 노출).
// - O029·O030(구흥서·이수복, 서울역사편찬원 구술)은 시트에 새로 추가된 구술 발췌 2건.
//   같은 시트에 있던 O027·O028(박돈서·문영일, mkoha)은 segment_text가 아직 비어 있어 제외했다 —
//   인용문 없는 발췌구간은 성립하지 않으므로, 시트에 원문이 채워지면 다음에 반영한다.

function seg(text: string): Utterance[] {
  return text.split("\n").map((line) => {
    const m = line.match(/^(면담자|구술자)\s*[:;]\s*(.*)$/);
    if (!m) return { role: "narrator" as const, text: line };
    return { role: m[1] === "면담자" ? ("interviewer" as const) : ("narrator" as const), text: m[2] };
  });
}

// sources_authority 탭에서, oral segments가 실제로 참조하는 출처만 옮겨왔다.
const SOURCES: Record<string, { title: string; url?: string }> = {
  SRC001: {
    title: "김청기 : 2017년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=153&isLooked=false#none",
  },
  SRC004: {
    title: "김성찬 : 2022년 한국영화사 구술채록 연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=701&isLooked=false#none",
  },
  SRC008: {
    title: "이순재1 : 2018년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=169&isLooked=false#none",
  },
  SRC009: {
    title: "정지영1 : 2024년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=1084&isLooked=false#none",
  },
  SRC010: {
    title: "신동헌 : 2008년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=841&isLooked=false#none",
  },
  SRC011: {
    title: "노만 : 2022년 한국영화사 구술채록 연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=761&isLooked=true#none",
  },
  SRC012: {
    title: "남궁원 : 2015년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=621&isLooked=false#none",
  },
  SRC013: {
    title: "하연남 : 2014년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=147&isLooked=false#none",
  },
  SRC014: {
    title: "안건호 : 2021년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=341&isLooked=false#none",
  },
  SRC015: {
    title: "박행철 : 2014년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=146&isLooked=true#none",
  },
  SRC016: {
    title: "최하원 : 2014년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=144&isLooked=true#none",
  },
  SRC017: {
    title: "김지헌 : 2014년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=145&isLooked=true#none",
  },
  SRC018: {
    title: "황의순 : 2013년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=143&isLooked=false#none",
  },
  SRC019: {
    title: "강범구 : 2011년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=114&isLooked=false#none",
  },
  SRC020: {
    title: "이달형 : 2017년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=154&isLooked=false#none",
  },
  SRC021: {
    title: "김동호 : 2019년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=170&isLooked=false#none",
  },
  SRC022: {
    title: "송길한 : 2019년 한국영화사 구술채록연구 시리즈 <생애사>",
    url: "https://www.kmdb.or.kr/collectionlist/detail/view?colId=171&isLooked=false#none",
  },
  SRC025: {
    title: "새벽종이 울렸네 새아침이 밝았네",
    url: "https://history.seoul.go.kr/archive/ebook/view.do?bookguid=CEA731BB-6EC5-45B8-8CEF-E80C9956938A&codeId=EBK0012&key=2211220003&pageIndex=1&orderBy=registDe+desc&sw=&arrSc=&period=&sc_wDateS=2026.07.11&sc_wDateE=2026.07.18&sw=&separator=and&sw=&separator=and",
  },
  SRC026: {
    title: "지하철 우리 자본과 기술로",
    url: "https://history.seoul.go.kr/archive/ebook/view.do?bookguid=D1D43F51-1776-43A5-9555-011746F0F3AC&codeId=EBK0012&key=2211220003&pageIndex=1&orderBy=registDe+desc&sw=&arrSc=&period=&sc_wDateS=2026.07.11&sc_wDateE=2026.07.18&sw=&separator=and&sw=&separator=and",
  },
};

// persons_authority 탭에서, oral segments의 구술자(narrator_id)만 옮겨왔다.
const PERSONS: Record<string, { name: string; birthYear: number }> = {
  P001: { name: "김청기", birthYear: 1941 },
  P004: { name: "김성찬", birthYear: 1938 },
  P006: { name: "이순재", birthYear: 1934 },
  P007: { name: "정지영", birthYear: 1946 },
  P008: { name: "신동헌", birthYear: 1927 },
  P010: { name: "노만", birthYear: 1935 },
  P011: { name: "남궁원", birthYear: 1934 },
  P013: { name: "하연남", birthYear: 1927 },
  P015: { name: "안건호", birthYear: 1934 },
  P016: { name: "박행철", birthYear: 1934 },
  P017: { name: "최하원", birthYear: 1937 },
  P018: { name: "김지헌", birthYear: 1930 },
  P019: { name: "황의순", birthYear: 1935 },
  P020: { name: "강범구", birthYear: 1924 },
  P022: { name: "이달형", birthYear: 1929 },
  P023: { name: "김동호", birthYear: 1937 },
  P024: { name: "송길한", birthYear: 1940 },
  P028: { name: "구흥서", birthYear: 1938 },
  P030: { name: "이수복", birthYear: 1939 },
};

export const chronicleEvents: TimelineEventData[] = [
  {
    id: "E001",
    eventName: "최초의 국산 라디오 생산(금성사)",
    dateValue: "1959-12-15",
    summary: "금성사가 부산 공장에서 최초의 국산 라디오를 생산했다.",
    sourceReference: "SRC002",
    places: [],
    keywordTags: ["라디오", "제조", "생산", "여공", "금성사", "부산"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E001-archives",
        type: "사진",
        title: "금성사라디오제조공장1 (1962)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200036473&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E002",
    eventName: "애니메이션 <태권동자 마루치 아라치> 제작",
    dateValue: "1977",
    summary: "라디오 연속극으로 인기를 얻은 <태권동자 마루치 아라치>가 애니메이션으로 제작됐다.",
    sourceReference: "SRC003",
    places: [],
    keywordTags: ["애니메이션", "태권도", "임정규"],
    linkedSegmentIds: ["O002", "O026"],
    linkedMaterials: [
      {
        id: "mat-E002",
        type: "사진",
        title: "<태권동자 마루치 아라치> 포스터 (placeholder)",
        sourceOrg: "사료 연동 전 목업",
        sourceUrl: "https://example.org/archive/photo/E002",
      },
    ],
  },
  {
    id: "E003",
    eventName: "경성방송국(JODK, 출력 1kW, 주파수 690kHz) 개국",
    dateValue: "1927-2-16",
    summary: "호출부호 JODK, 출력 1kW·주파수 690kHz로 경성방송국이 개국했다.",
    sourceReference: "SRC005; 근대사 연표(국사편찬위원회, 날짜 일치 확인)",
    places: [],
    keywordTags: ["라디오", "경성방송국", "서울중앙방송국", "개국"],
    linkedSegmentIds: ["O006"],
    linkedMaterials: [
      {
        id: "mat-E003-archives",
        type: "문서",
        title: "JODK 사라진 호출 부호 (1999)",
        sourceOrg: "친일반민족행위진상규명위원회 사무처 조사4팀 · 국가기록원",
        sourceUrl:
          "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=201003237763&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E004",
    eventName: "최초의 민영방송사 기독교방송(CBS) 라디오 방송(출력 5kW, 주파수 700kHz) 개시",
    dateValue: "1954-12-15",
    summary: "출력 5kW·주파수 700kHz로 최초의 민영방송 기독교방송(CBS)이 방송을 시작했다.",
    sourceReference: "SRC005; 대한민국사 연표(국사편찬위원회, 날짜 일치 확인)",
    places: [],
    keywordTags: ["라디오", "민영방송", "기독교방송", "CBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E005",
    eventName: "조선일보사 주최, 무선 전화 방송 공개 시연",
    dateValue: "1924-12-17",
    summary: "조선일보사 주최로 무선 전화 방송 공개 시연회가 열렸다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["무선전화", "시연", "조선일보"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E005",
        type: "신문",
        title: "무선 전화 방송 시연 기사 (placeholder)",
        sourceOrg: "사료 연동 전 목업",
        sourceUrl: "https://example.org/archive/newspaper/E005",
      },
    ],
  },
  {
    id: "E006",
    eventName: "일제, 국가 총동원령에 따라 국방 수신기 보급('한 집에 한 대 라디오 비치' 국방 표어)",
    dateValue: "1938",
    summary: "총동원령 아래 '한 집에 한 대 라디오 비치' 표어와 함께 국방 수신기가 보급됐다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["국방수신기", "보급"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E007",
    eventName: "문화방송(MBC) 개국(5kW, 900kHz)",
    dateValue: "1961-12-2",
    summary: "출력 5kW·주파수 900kHz로 문화방송(MBC)이 개국했다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E007-archives",
        type: "사진",
        title: "문화방송개국2주년기념제2회문화방송제1 (1963)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200059682&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E008",
    eventName: "동아방송(DBS) 개국(10kW, 1,230kHz[나중에 792kHz로 변경])",
    dateValue: "1963-4-25",
    summary: "출력 10kW·주파수 1,230kHz(후에 792kHz)로 동아방송(DBS)이 개국했다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E008-archives",
        type: "사진",
        title: "동아방송국개국기념공연3 (1963)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200058985&rc_ritem_no=000000000003",
      },
    ],
  },
  {
    id: "E009",
    eventName: "라디오서울(RSB, 이후 JBS를 거쳐 동양방송(TBC)으로 개칭) 개국(20kW, 1,380kHz)",
    dateValue: "1964-5-9",
    summary: "출력 20kW·주파수 1,380kHz로 라디오서울(RSB)이 개국했다. 이후 동양방송(TBC)으로 개칭된다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E009-archives",
        type: "사진",
        title: "라디오서울전속악단결성식1 (1964)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200056397&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E010",
    eventName: "언론사 통폐합",
    dateValue: "1980",
    summary: "신군부에 의해 언론사 통폐합이 단행됐다.",
    sourceReference: "SRC006",
    places: [],
    keywordTags: ["라디오", "언론사통폐합"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E010-archives",
        type: "문서",
        title: "1980년 언론사통폐합 언론인 강제해직사건 별첨 자료 (2009)",
        sourceOrg: "진실화해를위한과거사정리위원회 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=201104877586&rc_ritem_no=000000000002",
      },
    ],
  },
  {
    id: "E011",
    eventName: "이중방송(한국어, 일본어) 개시",
    dateValue: "1933-4-26",
    summary: "연희방송소에서 한국어·일본어 이중방송이 시작됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오", "연희방송소", "이중방송"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E012",
    eventName: "단파방송 밀청사건",
    dateValue: "1942-12-24",
    summary:
      "개성 송신소 직원 송진근·박용신이 미국 샌프란시스코발 〈미국의 소리〉 단파 방송을 몰래 들은 혐의로 체포됐다. 날짜는 국사편찬위원회 대한민국사 연표 기준으로 보정(기존 SRC007엔 1942년 12월로만 기록).",
    sourceReference: "SRC007; 대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E013",
    eventName: "일본 항복방송",
    dateValue: "1945-8-15",
    summary: "일왕의 항복 선언이 라디오로 방송됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오", "패전", "항복", "일제"],
    linkedSegmentIds: ["O010", "O016"],
    linkedMaterials: [
      {
        id: "mat-E013",
        type: "신문",
        title: "항복방송 보도 지면 (placeholder)",
        sourceOrg: "사료 연동 전 목업",
        sourceUrl: "https://example.org/archive/newspaper/E013",
      },
    ],
  },
  {
    id: "E014",
    eventName: "미군정청, 서울중앙방송국(KBS) 접수",
    dateValue: "1945-9-15",
    summary: "미군정청이 서울중앙방송국을 접수했다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E015",
    eventName: "정시방송제 실시",
    dateValue: "1946-10-18",
    summary: "정해진 시각에 맞춰 편성하는 정시방송제가 실시됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E016",
    eventName: "호출부호 HL 배정",
    dateValue: "1947-10-2",
    summary:
      "국제무선통신회의에서 한국에 호출부호 HL이 배정됐다. 🔍 이견: SRC007엔 1947년 9월 3일로 기록되어 있으나, 국사편찬위원회 대한민국사 연표는 10월 2일(방송 콜 사인 HL 사용 개시)로 기록 — 더 정밀한 후자 날짜로 보정.",
    sourceReference: "SRC007; 대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E017",
    eventName: "제14회 런던 올림픽 중계",
    dateValue: "1948-7-29",
    summary: "제14회 런던 올림픽이 라디오로 중계됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E018",
    eventName: "대한방송협회 국영화",
    dateValue: "1948-8-7",
    summary: "대한방송협회가 국영 체제로 전환됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E019",
    eventName: "라디오 청취료 폐지",
    dateValue: "1951-4-3",
    summary: "라디오 청취료가 폐지됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오", "청취료"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E020",
    eventName: "KBS 라디오 연속극 '청실홍실' 방송",
    dateValue: "1956-12-2~",
    summary: "KBS 라디오에서 연속극 '청실홍실' 방송이 시작됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오", "연속극"],
    linkedSegmentIds: ["O017"],
    linkedMaterials: [
      {
        id: "mat-E020",
        type: "신문",
        title: "'청실홍실' 편성 안내 (placeholder)",
        sourceOrg: "사료 연동 전 목업",
        sourceUrl: "https://example.org/archive/newspaper/E020",
      },
    ],
  },
  {
    id: "E021",
    eventName: "서울중앙방송국(KBS) 남산연주소 준공",
    dateValue: "1957-12-10",
    summary: "서울중앙방송국 남산연주소가 준공됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E021-archives",
        type: "사진",
        title: "남산연주소외경 (1957)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200057642&rc_ritem_no=000000000004",
      },
    ],
  },
  {
    id: "E022",
    eventName: "농어촌 라디오 보내기 사업 시작",
    dateValue: "1958",
    summary: "난시청 농어촌 지역에 라디오를 보급하는 사업이 시작됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: ["O024"],
    linkedMaterials: [
      {
        id: "mat-E022-archives",
        type: "문서",
        title: "농어촌에라디오스피카보내기운동 (1966)",
        sourceOrg: "전라남도 순천시 기획실 공보담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200300826660&rc_ritem_no=000000000042",
      },
    ],
  },
  {
    id: "E023",
    eventName: "국산 라디오 생산",
    dateValue: "1959-11-15",
    summary: "국산 라디오 생산이 시작됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E023-archives",
        type: "문서",
        title: "국산 라디오 생산(제1회) (1960)",
        sourceOrg: "총무처 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200400011256&rc_ritem_no=000000000012",
      },
    ],
  },
  {
    id: "E024",
    eventName: "MBC 문화방송 '별이 빛나는 밤에' 방송 시작",
    dateValue: "1969-3-17",
    summary: "MBC 라디오에서 '별이 빛나는 밤에' 방송이 시작됐다.",
    sourceReference: "SRC007; 대한민국사 연표(국사편찬위원회, 날짜 일치 확인)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E024-archives",
        type: "문서",
        title: "라디오 별이 빛나는 밤에 (2000)",
        sourceOrg: "방송위원회 사무처 매체정책국 뉴미디어부 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=201104900824&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E025",
    eventName: "한국방송공사(KBS) 창립",
    dateValue: "1973-3-3",
    summary: "국영방송이 공사 체제로 전환되며 한국방송공사(KBS)가 창립됐다.",
    sourceReference: "SRC007",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [
      {
        id: "mat-E025-archives",
        type: "사진",
        title: "한국방송공사창립기념식1 (1973)",
        sourceOrg: "공보처 홍보국 사진담당관 · 국가기록원",
        sourceUrl: "http://www.archives.go.kr/next/newsearch/showDetailPopup.do?rc_code=1310377&rc_rfile_no=200200064800&rc_ritem_no=000000000001",
      },
    ],
  },
  {
    id: "E026",
    eventName: "경성 방송국(JODK) 성립",
    dateValue: "1926-11-30",
    summary: "경성 방송국(JODK) 성립",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "경성"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E027",
    eventName: "경성방송국, 라디오 무가입 청취자를 〈전화법〉 위반으로 단속",
    dateValue: "1927-04-06",
    summary: "경성방송국, 라디오 무가입 청취자를 〈전화법〉 위반으로 단속",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "경성"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E028",
    eventName: "부산방송국(JBAK) 개국",
    dateValue: "1935-09-20",
    summary: "부산방송국(JBAK) 개국",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "부산"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E029",
    eventName: "전국의 라디오 청취자 총 45,415명, 한국인 11,758명·일본인 33,383명 기타 외국인 264명",
    dateValue: "1935-09-30",
    summary: "전국의 라디오 청취자 총 45,415명, 한국인 11,758명·일본인 33,383명 기타 외국인 264명",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E030",
    eventName: "평양 방송국 설립",
    dateValue: "1936-03-26",
    summary: "평양 방송국 설립",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "평양"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E031",
    eventName: "평양 방송국 개소식 및 준공식 거행",
    dateValue: "1936-11-15",
    summary: "평양 방송국 개소식 및 준공식 거행",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "평양"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E032",
    eventName: "전남 광주 방송국 개국",
    dateValue: "1942-03-21",
    summary: "전남 광주 방송국 개국",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "광주"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E033",
    eventName: "이승만, 미국의 소리 방송을 통해 동양·남미의 동포 격려",
    dateValue: "1942-07-06",
    summary: "이승만, 미국의 소리 방송을 통해 동양·남미의 동포 격려",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E034",
    eventName: "대한민국 임시정부 선전부, 중경 방송국 통해 우리말 방송 개시",
    dateValue: "1944-04-02",
    summary: "대한민국 임시정부 선전부, 중경 방송국 통해 우리말 방송 개시",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E035",
    eventName: "건국 준비 위원회, 국내 치안권 인수·방송국 언론 기관 등 접수",
    dateValue: "1945-08-17",
    summary: "건국 준비 위원회, 국내 치안권 인수·방송국 언론 기관 등 접수",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E036",
    eventName: "미국, 미군 인천 상륙 후에 미·소 양군이 북위 38도선 분할 점령 방송",
    dateValue: "1945-08-25",
    summary: "미국, 미군 인천 상륙 후에 미·소 양군이 북위 38도선 분할 점령 방송",
    sourceReference: "근대사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E037",
    eventName: "제2방송(970KHz), 제1방송으로 변경·우리말 방송 개시, 제1방송(710KHz·일어) 폐지",
    dateValue: "1945-09-09",
    summary: "제2방송(970KHz), 제1방송으로 변경·우리말 방송 개시, 제1방송(710KHz·일어) 폐지",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E038",
    eventName: "모스크바 방송, 한국의 신탁 통치 기간 미국 10년, 소련 5년 주장",
    dateValue: "1946-01-24",
    summary: "모스크바 방송, 한국의 신탁 통치 기간 미국 10년, 소련 5년 주장",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E039",
    eventName: "조선 불교 중앙 총무원, 한글 보급과 불교 교리 전파 목적에 해동역경원(海東驛經院) 설치",
    dateValue: "1946-01-25",
    summary: "조선 불교 중앙 총무원, 한글 보급과 불교 교리 전파 목적에 해동역경원(海東驛經院) 설치",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E040",
    eventName: "자유 대한의 소리(Voice of Free Korea), 영어 방송 개시(해외 방송의 시초)",
    dateValue: "1953-08-15",
    summary: "자유 대한의 소리(Voice of Free Korea), 영어 방송 개시(해외 방송의 시초)",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E041",
    eventName: "국내 첫 텔레비전 방송국(HLKZ) 개국",
    dateValue: "1956-05-12",
    summary: "국내 첫 텔레비전 방송국(HLKZ) 개국",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "HLKZ"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E042",
    eventName: "미군 방송 AFKN-TV, 방송 개시",
    dateValue: "1958-09-15",
    summary: "미군 방송 AFKN-TV, 방송 개시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "AFKN"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E043",
    eventName: "미군 방송 AFKN－TV, 자체 제작 생방송 개시",
    dateValue: "1959-01-04",
    summary: "미군 방송 AFKN－TV, 자체 제작 생방송 개시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "AFKN"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E044",
    eventName: "서울 민간 방송 주식회사(MBC) 설립 인가",
    dateValue: "1961-01-28",
    summary: "서울 민간 방송 주식회사(MBC) 설립 인가",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E045",
    eventName: "서울 민간 방송 주식 회사(MBC) 창립",
    dateValue: "1961-02-21",
    summary: "서울 민간 방송 주식 회사(MBC) 창립",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E046",
    eventName: "KBS-TV 시험 방송",
    dateValue: "1961-12-24",
    summary: "KBS-TV 시험 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E047",
    eventName: "KBS 라디오, 〈김삿갓 북한 방랑기〉 첫 방송",
    dateValue: "1964-05-18",
    summary: "KBS 라디오, 〈김삿갓 북한 방랑기〉 첫 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E048",
    eventName: "중앙정보부, 방송극 〈송아지〉 작가 김정욱, 반공법 위반 혐의로 구속",
    dateValue: "1965-03-04",
    summary: "중앙정보부, 방송극 〈송아지〉 작가 김정욱, 반공법 위반 혐의로 구속",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E049",
    eventName: "박정희 대통령, 국영 텔레비전(KBS)에 광고 방송 없이 운영토록 지시",
    dateValue: "1969-01-16",
    summary: "박정희 대통령, 국영 텔레비전(KBS)에 광고 방송 없이 운영토록 지시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E050",
    eventName: "중앙 방송국, 첫 TV 교육 방송 실시",
    dateValue: "1969-05-01",
    summary: "중앙 방송국, 첫 TV 교육 방송 실시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E051",
    eventName: "KBS 텔레비전, 아폴로 11호 착륙 중계",
    dateValue: "1969-07-16",
    summary: "KBS 텔레비전, 아폴로 11호 착륙 중계",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E052",
    eventName: "문화 방송 텔레비전(MBC) 개국, 호출 부호 HLKV·채널 11",
    dateValue: "1969-08-08",
    summary: "문화 방송 텔레비전(MBC) 개국, 호출 부호 HLKV·채널 11",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC", "HLKV"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E053",
    eventName: "방송 윤리 위원회, 방송 프로 사전 심의 및 방송국·무선국 허가 갱신 문제로 파문",
    dateValue: "1970-01-15",
    summary: "방송 윤리 위원회, 방송 프로 사전 심의 및 방송국·무선국 허가 갱신 문제로 파문",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E054",
    eventName: "KBS 1 TV, 첫 아침 방송 실시",
    dateValue: "1970-04-13",
    summary: "KBS 1 TV, 첫 아침 방송 실시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E055",
    eventName: "조선·동아·중앙·동양방송 기자들, 〈언론 자유 수호 선언〉 발표",
    dateValue: "1971-04-17",
    summary: "조선·동아·중앙·동양방송 기자들, 〈언론 자유 수호 선언〉 발표",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "동양방송"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E056",
    eventName: "남산 종합 타워 송신 개시",
    dateValue: "1972-04-03",
    summary: "남산 종합 타워 송신 개시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E057",
    eventName: "제3방송을 통한 방송 통신 대학(2년제) 개강",
    dateValue: "1972-06-01",
    summary: "제3방송을 통한 방송 통신 대학(2년제) 개강",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E058",
    eventName: "대한민국 방송반, 남북 적십자 회담 제1차 본회담 평양에서 중계",
    dateValue: "1972-08-30",
    summary: "대한민국 방송반, 남북 적십자 회담 제1차 본회담 평양에서 중계",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "평양"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E059",
    eventName: "다큐멘터리 한국방송공사 〈인간승리〉, 제5회 방송 대상 프로그램 콘테스트 최우수상 시상",
    dateValue: "1972-10-02",
    summary: "다큐멘터리 한국방송공사 〈인간승리〉, 제5회 방송 대상 프로그램 콘테스트 최우수상 시상",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E060",
    eventName: "라디오 307만 대(2가구에 1대)·텔레비전 81만 대(7가구에 1대) 보급",
    dateValue: "1972-10-10",
    summary: "라디오 307만 대(2가구에 1대)·텔레비전 81만 대(7가구에 1대) 보급",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E061",
    eventName: "중앙일보·동양방송 기자 150여 명, 언론 기본권 회복 요구 선언문 발표",
    dateValue: "1973-11-30",
    summary: "중앙일보·동양방송 기자 150여 명, 언론 기본권 회복 요구 선언문 발표",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "동양방송"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E062",
    eventName: "동아일보·동아방송 기자들, 민권 회복 가톨릭 기도회 보도 문제로 제작 거부",
    dateValue: "1974-11-12",
    summary: "동아일보·동아방송 기자들, 민권 회복 가톨릭 기도회 보도 문제로 제작 거부",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "동아방송"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E063",
    eventName: "16개 대기업 광고주, ‘동아 방송’의 광고 방송 해약, 광고 중단",
    dateValue: "1975-01-07",
    summary: "16개 대기업 광고주, ‘동아 방송’의 광고 방송 해약, 광고 중단",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E064",
    eventName: "한국일보·조선일보·중앙일보·동양방송 기자들, 언론 자유 수호 제3 선언문 채택",
    dateValue: "1975-01-14",
    summary: "한국일보·조선일보·중앙일보·동양방송 기자들, 언론 자유 수호 제3 선언문 채택",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "동양방송"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E065",
    eventName: "한국 방송 윤리 위원회, 〈왜 불러〉·〈불꽃〉 등 6곡 방송 금지",
    dateValue: "1975-12-10",
    summary: "한국 방송 윤리 위원회, 〈왜 불러〉·〈불꽃〉 등 6곡 방송 금지",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E066",
    eventName: "연예인 24명 방송 출연 금지, 심수봉 등 가수 7명·탤런트 13명·이주일 등 코미디언 4명",
    dateValue: "1980-08-31",
    summary: "연예인 24명 방송 출연 금지, 심수봉 등 가수 7명·탤런트 13명·이주일 등 코미디언 4명",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E067",
    eventName: "동아방송·TBC, KBS로 통폐합",
    dateValue: "1980-10-30",
    summary: "동아방송·TBC, KBS로 통폐합",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS", "동아방송", "TBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E068",
    eventName: "KBS, 〈전국 노래 자랑〉 첫 방영",
    dateValue: "1980-11-09",
    summary: "KBS, 〈전국 노래 자랑〉 첫 방영",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E069",
    eventName: "동아(DBS)·동양(TBC)·서해·전일방송 종영 방송",
    dateValue: "1980-11-30",
    summary: "동아(DBS)·동양(TBC)·서해·전일방송 종영 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "TBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E070",
    eventName: "컬러 텔레비전 방송, 수출의 날 기념식 중계 방송으로 시작",
    dateValue: "1980-12-01",
    summary: "컬러 텔레비전 방송, 수출의 날 기념식 중계 방송으로 시작",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E071",
    eventName: "한국 방송 광고 공사(사장 홍두표) 발족",
    dateValue: "1981-01-22",
    summary: "한국 방송 광고 공사(사장 홍두표) 발족",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E072",
    eventName: "한국 방송 공사(KBS), 교육 텔레비전 첫 방송",
    dateValue: "1981-02-02",
    summary: "한국 방송 공사(KBS), 교육 텔레비전 첫 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E073",
    eventName: "한국 방송 공사, TV 방송 통한 이산 가족 찾기 사업 시작",
    dateValue: "1983-06-30",
    summary: "한국 방송 공사, TV 방송 통한 이산 가족 찾기 사업 시작",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E074",
    eventName: "KBS 이산 가족 상봉, 첫 부부 만남",
    dateValue: "1983-07-17",
    summary: "KBS 이산 가족 상봉, 첫 부부 만남",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E075",
    eventName: "KBS 이산 가족 찾기 생방송 마감, 10만 952건 신청·5만 3536명 소개·1만 189가족 혈육 상봉",
    dateValue: "1983-11-14",
    summary: "KBS 이산 가족 찾기 생방송 마감, 10만 952건 신청·5만 3536명 소개·1만 189가족 혈육 상봉",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E076",
    eventName: "북한 평양방송, 김정일 비서를 김일성 주석의 후계자로 공식 지칭",
    dateValue: "1984-08-05",
    summary: "북한 평양방송, 김정일 비서를 김일성 주석의 후계자로 공식 지칭",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "평양"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E077",
    eventName: "신민당, KBS 텔레비전 뉴스 안보기, 시청료 거부 운동 당론 결정",
    dateValue: "1986-03-08",
    summary: "신민당, KBS 텔레비전 뉴스 안보기, 시청료 거부 운동 당론 결정",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E078",
    eventName: "코미디언 김병조, 민주정의당 전당 대회 발언 물의로 MBC 방송 일시 출연 정지",
    dateValue: "1987-06-12",
    summary: "코미디언 김병조, 민주정의당 전당 대회 발언 물의로 MBC 방송 일시 출연 정지",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E079",
    eventName: "방송 심의 위원회, 방송금지 가요 5백 곡 해제",
    dateValue: "1987-09-05",
    summary: "방송 심의 위원회, 방송금지 가요 5백 곡 해제",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E080",
    eventName: "문화공보부, 국기 강하와 영화 상영 때에 애국가 방송 폐지 발표(1.23. 시행)",
    dateValue: "1989-01-20",
    summary: "문화공보부, 국기 강하와 영화 상영 때에 애국가 방송 폐지 발표(1.23. 시행)",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E081",
    eventName: "문화공보부, 불교방송(BBS)과 평화방송(PBC) 설립 인가",
    dateValue: "1989-03-02",
    summary: "문화공보부, 불교방송(BBS)과 평화방송(PBC) 설립 인가",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E082",
    eventName: "KBS라디오 프로듀서 60여 명, 노태우 대통령의 라디오 주례 방송의 절차·방법 문제로 첫 방송 거부 결의",
    dateValue: "1989-06-03",
    summary: "KBS라디오 프로듀서 60여 명, 노태우 대통령의 라디오 주례 방송의 절차·방법 문제로 첫 방송 거부 결의",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E083",
    eventName: "프로야구 MBC 청룡팀, 럭키 금성으로 양도돼 LG트윈스로 새 출발",
    dateValue: "1990-01-18",
    summary: "프로야구 MBC 청룡팀, 럭키 금성으로 양도돼 LG트윈스로 새 출발",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E084",
    eventName: "KBS·MBC의 PD 6명, 유명 가수 출연 조건으로 상납 받아 서울 지방 검찰청에 구속",
    dateValue: "1990-01-25",
    summary: "KBS·MBC의 PD 6명, 유명 가수 출연 조건으로 상납 받아 서울 지방 검찰청에 구속",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E085",
    eventName: "경찰, 병력을 한국 방송 공사에 투입하여 서기원 사장 취임 반대 농성 중인 노조원 2백여 명 연행",
    dateValue: "1990-04-12",
    summary: "경찰, 병력을 한국 방송 공사에 투입하여 서기원 사장 취임 반대 농성 중인 노조원 2백여 명 연행",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E086",
    eventName: "한국 방송 공사에 경찰 1천여 명 투입, 농성 노조원 강제 해산, 333명 연행",
    dateValue: "1990-04-30",
    summary: "한국 방송 공사에 경찰 1천여 명 투입, 농성 노조원 강제 해산, 333명 연행",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E087",
    eventName: "민주자유당, 국회 본회의에서 〈방송 관계 법안〉·〈광주 보상 법안〉 등 26개 안건 변칙 처리",
    dateValue: "1990-07-14",
    summary: "민주자유당, 국회 본회의에서 〈방송 관계 법안〉·〈광주 보상 법안〉 등 26개 안건 변칙 처리",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "광주"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E088",
    eventName: "태영건설, 채널 6번 새 민영 텔레비전 방송국의 지배 주주로 선정",
    dateValue: "1990-10-31",
    summary: "태영건설, 채널 6번 새 민영 텔레비전 방송국의 지배 주주로 선정",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E089",
    eventName: "SBS 라디오 방송국 개국",
    dateValue: "1991-03-20",
    summary: "SBS 라디오 방송국 개국",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "SBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E090",
    eventName: "SBS, 광주 민주화 운동 다룬 드라마 〈모래시계〉 첫 방송",
    dateValue: "1995-01-09",
    summary: "SBS, 광주 민주화 운동 다룬 드라마 〈모래시계〉 첫 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "SBS", "광주"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E091",
    eventName: "MBC 프로듀서 전원, 경찰의 프로듀서 비리 수사에 항의 사표 제출 결정",
    dateValue: "1995-02-11",
    summary: "MBC 프로듀서 전원, 경찰의 프로듀서 비리 수사에 항의 사표 제출 결정",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E092",
    eventName: "박찬종 서울시장 후보, SBS 녹화 텔레비전 토론에서 유신 찬양 시비로 방송 녹화 중단 사태",
    dateValue: "1995-06-18",
    summary: "박찬종 서울시장 후보, SBS 녹화 텔레비전 토론에서 유신 찬양 시비로 방송 녹화 중단 사태",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "SBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E093",
    eventName: "국제 방송 교류 재단, 외국어 전용 방송 아리랑텔레비전(채널 50) 개국",
    dateValue: "1997-02-03",
    summary: "국제 방송 교류 재단, 외국어 전용 방송 아리랑텔레비전(채널 50) 개국",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "아리랑"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E094",
    eventName: "MBC 농촌 드라마 ＜전원일기＞, 8백 회 자축 행사 개최",
    dateValue: "1997-03-03",
    summary: "MBC 농촌 드라마 ＜전원일기＞, 8백 회 자축 행사 개최",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E095",
    eventName: "한국 PD 연합회, 표절 가요 판정곡의 가요·쇼 프로그램 방송 금지 결정",
    dateValue: "1997-03-24",
    summary: "한국 PD 연합회, 표절 가요 판정곡의 가요·쇼 프로그램 방송 금지 결정",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E096",
    eventName: "MBC, 일본이 조선총독부 통해 ‘군 위안부’ 조직적 동원했다는 극비 암호문서 공개",
    dateValue: "1997-08-16",
    summary: "MBC, 일본이 조선총독부 통해 ‘군 위안부’ 조직적 동원했다는 극비 암호문서 공개",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E097",
    eventName: "서울 금란교회 신도 1천여 명, MBC 〈시사매거진 2580〉의 기독교 대한 감리회 감독회장 김홍도 목사의 비리 보도에 항의 시위",
    dateValue: "1998-04-11",
    summary: "서울 금란교회 신도 1천여 명, MBC 〈시사매거진 2580〉의 기독교 대한 감리회 감독회장 김홍도 목사의 비리 보도에 항의 시위",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E098",
    eventName: "한국 방송 공사 노동 조합, 프로그램 〈조선일보를 해부한다〉 등 방송 촉구 농성",
    dateValue: "1998-05-07",
    summary: "한국 방송 공사 노동 조합, 프로그램 〈조선일보를 해부한다〉 등 방송 촉구 농성",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E099",
    eventName: "KBS, 사육 수달을 야생 수달로 조작한 다큐 방송 사실 확인",
    dateValue: "1998-06-19",
    summary: "KBS, 사육 수달을 야생 수달로 조작한 다큐 방송 사실 확인",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E100",
    eventName: "문화방송, 미니시리즈 〈청춘〉의 일본 후지텔레비젼 드라마 표절 문제로 공개 사과",
    dateValue: "1999-03-30",
    summary: "문화방송, 미니시리즈 〈청춘〉의 일본 후지텔레비젼 드라마 표절 문제로 공개 사과",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E101",
    eventName: "만민 중앙 교회 신도들, 문화방송 〈PD수첩〉 방영 중 난입해 방송 중단",
    dateValue: "1999-05-11",
    summary: "만민 중앙 교회 신도들, 문화방송 〈PD수첩〉 방영 중 난입해 방송 중단",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E102",
    eventName: "문화방송, 이근안 전 경감 배후에 국가 안전 기획부·경찰 고위층 개입 보도",
    dateValue: "1999-11-07",
    summary: "문화방송, 이근안 전 경감 배후에 국가 안전 기획부·경찰 고위층 개입 보도",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E103",
    eventName: "미 CBS방송, 6·25 전쟁 당시 미군의 피난민 기총 사격 지시 문서 발견 보도",
    dateValue: "2000-06-06",
    summary: "미 CBS방송, 6·25 전쟁 당시 미군의 피난민 기총 사격 지시 문서 발견 보도",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "CBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E104",
    eventName: "한국 교육 방송 공사(EBS), 창립식 개최·공사 출범",
    dateValue: "2000-06-30",
    summary: "한국 교육 방송 공사(EBS), 창립식 개최·공사 출범",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "EBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E105",
    eventName: "북한 조선 중앙 텔레비전, 사상 최초로 EBS 제작 호랑이 관련 다큐멘터리 방송",
    dateValue: "2000-11-18",
    summary: "북한 조선 중앙 텔레비전, 사상 최초로 EBS 제작 호랑이 관련 다큐멘터리 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "EBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E106",
    eventName: "KBS, 여론 조사에서 김정일 국방 위원장 답방에 88% 찬성 보도",
    dateValue: "2001-06-14",
    summary: "KBS, 여론 조사에서 김정일 국방 위원장 답방에 88% 찬성 보도",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E107",
    eventName: "MBC, 고화질 텔레비전용 HDTV 다큐멘터리 첫 방송",
    dateValue: "2001-09-02",
    summary: "MBC, 고화질 텔레비전용 HDTV 다큐멘터리 첫 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E108",
    eventName: "MBC, 1990년 이후 이산 가족 상봉 신청자 11만 7천 명 중 1만 3천 명 사망 보도",
    dateValue: "2001-10-07",
    summary: "MBC, 1990년 이후 이산 가족 상봉 신청자 11만 7천 명 중 1만 3천 명 사망 보도",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E109",
    eventName: "국내 최초의 디지털 위성 방송 스카이라이프 개국",
    dateValue: "2002-03-01",
    summary: "국내 최초의 디지털 위성 방송 스카이라이프 개국",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "위성", "스카이라이프"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E110",
    eventName: "방송사 노동 조합·기술자, 디지털 텔레비전 전송 방식을 미국식에서 유럽식으로 변경 촉구",
    dateValue: "2002-06-11",
    summary: "방송사 노동 조합·기술자, 디지털 텔레비전 전송 방식을 미국식에서 유럽식으로 변경 촉구",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E111",
    eventName: "2002 MBC 평양 특별 공연, 북한 동평양 대극장에서 개최. 이미자 공연",
    dateValue: "2002-09-27",
    summary: "2002 MBC 평양 특별 공연, 북한 동평양 대극장에서 개최. 이미자 공연",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC", "평양"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E112",
    eventName: "중앙 선거 관리 위원회, 노무현 대통령의 방송 기자 클럽 초청 회견 발언, 〈선거법〉 9조 위반 결론",
    dateValue: "2004-03-03",
    summary: "중앙 선거 관리 위원회, 노무현 대통령의 방송 기자 클럽 초청 회견 발언, 〈선거법〉 9조 위반 결론",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E113",
    eventName: "방송 위원회, KBS·MBC·SBS의 노무현 대통령 탄핵 관련 보도에 권고 조치",
    dateValue: "2004-03-31",
    summary: "방송 위원회, KBS·MBC·SBS의 노무현 대통령 탄핵 관련 보도에 권고 조치",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "KBS", "MBC", "SBS"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E114",
    eventName: "교육인적자원부, 6월 모의 대학 수학 능력 시험부터 교육 방송 대학 수학 능력 시험 강의 내용 출제 반영 발표",
    dateValue: "2004-04-05",
    summary: "교육인적자원부, 6월 모의 대학 수학 능력 시험부터 교육 방송 대학 수학 능력 시험 강의 내용 출제 반영 발표",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E115",
    eventName: "조영길 국방 장관, 북한 경비정의 무선 송신 보고 누락 파문으로 사의 표명",
    dateValue: "2004-07-27",
    summary: "조영길 국방 장관, 북한 경비정의 무선 송신 보고 누락 파문으로 사의 표명",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E116",
    eventName: "위성 DMB 사업자 TU미디어, 시험 방송 개시",
    dateValue: "2005-01-10",
    summary: "위성 DMB 사업자 TU미디어, 시험 방송 개시",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "위성", "DMB"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E117",
    eventName: "MBC PD수첩, 〈황우석 신화의 난자 매매 의혹〉 방송",
    dateValue: "2005-11-22",
    summary: "MBC PD수첩, 〈황우석 신화의 난자 매매 의혹〉 방송",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E118",
    eventName: "MBC, PD수첩의 취재 윤리 위반 관련 대국민 사과",
    dateValue: "2005-12-04",
    summary: "MBC, PD수첩의 취재 윤리 위반 관련 대국민 사과",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오", "MBC"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E119",
    eventName: "서울 행정 법원, KT＆G의 담배 방송 광고 금지 판결",
    dateValue: "2007-02-07",
    summary: "서울 행정 법원, KT＆G의 담배 방송 광고 금지 판결",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
  {
    id: "E120",
    eventName: "한나라당, BBK 주가 조작 사건 관련 모든 방송 토론 거부",
    dateValue: "2007-11-22",
    summary: "한나라당, BBK 주가 조작 사건 관련 모든 방송 토론 거부",
    sourceReference: "대한민국사 연표(국사편찬위원회)",
    places: [],
    keywordTags: ["라디오"],
    linkedSegmentIds: [],
    linkedMaterials: [],
  },
];

export const oralSegments: SegmentCardData[] = [
  {
    id: "O001",
    itemTitle: "김청기(1941) 구술 (78–79쪽)",
    dateValue: "1940?/1949?",
    utterances: seg(
      "구술자: 전쟁 전에는 라디오라는 거밖에 없었어. 우리 집에. 그래도 그게 그 당시면 '재산목록 1호' 그랬잖아. '자전거가 1호, 라디오가 2호' 이런 식으로. 선풍기가 3혼가 하여튼 그랬어. 재산목록 써 가져 가, 학교. 그런 거 조사가 있다고.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC001"],
    relatedItems: [],
  },
  {
    id: "O002",
    itemTitle: "김청기(1941) 구술 (142–143쪽)",
    dateValue: "1974",
    utterances: seg(
      "면담자: 이게 <태권동자 마루치 아라치>잖아요?\n구술자: 그건 그때 굉장히 히트 했었어. 저 라디오 방송에, 동아방송인가 하여튼 엄청 히트 했었지. 그 판권을 사 가지고 하니깐 그건 그때 재미 봤어. 그런데도 그거 해서 뭐 손해 봤는지 어찌 됐든 김일환 씨 더 이상 제작 않고 그냥 그러대. 재미 봤으면 계속 했었을 텐데. 근데 하여튼 아이들 영화는 여러 개 나오면 다 안 돼. 어린이영화는 쪼개져 가지고 안 돼. 하나 보여줬는데 또 보여줄 부모가 그렇게 많지 않았어. 그때는. 시간도 그렇고 돈도 그렇고.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오", "연속극", "아동극"],
    hasDiscrepancy: false,
    notes: "동아방송이 아닌 MBC에서 방영됐다.",
    sourceRef: SOURCES["SRC001"],
    relatedItems: [],
  },
  {
    id: "O003",
    itemTitle: "김성찬(1938) 구술 (49쪽)",
    dateValue: "1950~",
    utterances: seg(
      "구술자: 전기 서적이, 서적도 없었지만은 라디오 진공관 시대니까. 라디오 같은 것도 만들고 우리가 소리를 듣고 그랬어요. 그런데 취미가 상당히 있었던 거 같아요, 내가. 결국은 녹음 계통에 오게 된 동기도 그런 동기인 것 같고, 관심 있었고. 녹음도 그 전기를 알아야 되거든요.\n면담자: 라디오는 어떻게 만드나요?\n구술자: 아, 그때는 《무센토짓켄(無線と実験, むせんとじっけん)》, 그러니까 일본말을 알았어요. 일본 서적들이 있어. 《무센토》지. 그 '무선과 실험'이라는 일본 책 보아 가면서 배선도(配線圖) 보고. 배선도 보고 조립하고 하다가 이렇게. 부품은 그때 라디오방 가서 좀 사오기도 하고 그래서. 만들고 나면 간단해요, 사실은. 라디오 소리가 들린다는 걸 어렵게 생각하지만은 그때 만든 때는 배선대로 이렇게 조립하면 되는 거니까. 그런 기억이 나요.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오", "진공관"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC004"],
    relatedItems: [],
  },
  {
    id: "O004",
    itemTitle: "이순재(1934) 구술 (167쪽)",
    dateValue: "1960?",
    utterances: seg(
      "면담자: 네. KBS라디오에 <인민군에게 보내는 시간>이라는 거를.\n구술자: 어. 그거는 우리가 한 시간ㄱ짜리를 만들어서 KBS2를 통해서 이북에다 쏘는 거야. 그게 <인민군에게 보내는 시간>이야. 그걸 우리가 한 프로 제작을 했다고.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오드라마", "대북방송"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC008"],
    relatedItems: [],
  },
  {
    id: "O005",
    itemTitle: "정지영(1946) 구술 (142쪽)",
    dateValue: "1987-6-29",
    utterances: seg(
      "구술자: 내가 <TV문학관>에 한 작품 했어. 그때 나왔어. 그게. 근데 재밌는 거는 그 작품을 찍고 있을 때 6.29선언이 터졌어요. 내가 통영에서 그 작품을 찍고 있었는데. 버스에 타고 있는데 버스 라디오에서 6.29 선언이 탁 나오더라구. (웃음) 그러니까 6.29 선언으로 뭐 한 달 만에 풀린 거지.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC009"],
    relatedItems: [],
  },
  {
    id: "O006",
    itemTitle: "신동헌(1927) 구술 (78쪽)",
    dateValue: "1945~",
    utterances: seg(
      "구술자: 그담에 고향도 해방되면서부터 이제 전기가 들어오기 시작해서.｛아아｝그래서 라디오도. 그때 라디오는 그때만 해도, 우리가 있을 때만 해도 서울방송이랑 다 자유롭게 들을 땝니다. 그게. 그래 밤낮 서울... 게서 그때 그 서울방송 들었는데, 그때 이제 보니까 그 경성방송국이란 게 있죠?",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC010"],
    relatedItems: [],
  },
  {
    id: "O007",
    itemTitle: "노만(1935) 구술 (32쪽)",
    dateValue: "",
    utterances: seg(
      "구술자: 일제시대는 우리 동네 전기가 안 들어왔었어요. 근데 그 묘하게, 광량만(廣粱灣)이래는 데만, 거기서 우리가 한 5리 정도 떨어져 있는데, 거기까지만 전기 들어오고 우리는 해방되자마자 전기가 이제 들어왔는데, 일제시대 때는 전기가 없었습니다. 그래가지고 라디오도 트랜지스타(transistor) 라디오를 우리가 들었으니까.\n면담자: 그럼 전기도 안 들어오고 조금 놀거리가 마땅치 않았을 거 같은데 선생님 어린 시절에는 어떤, 문화생활 같은 거는 조금 꿈꾸기가 어려우셨던가요?\n구술자: 그렇죠. 문화생활은 진짜 힘들었고. 그런데, 시골이지만 우리는 신문도 봤고, 라디오가 있으니까 라디오 들었고. 8.15 때 천황 항복 저거 라디오도 우리가 들었어요. 그럴 정도로 우리가 좀 유복한 생활을 했다고 그럴까.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오"],
    hasDiscrepancy: false,
    notes: "구술자는 트랜지스터 라디오가 아니라 진공관 전지 라디오로 정정하였다.",
    sourceRef: SOURCES["SRC011"],
    relatedItems: [],
  },
  {
    id: "O008",
    itemTitle: "남궁원(1934) 구술 (55쪽)",
    dateValue: "",
    utterances: seg(
      "면담자: 어머님 아버님께서 약간 신식 문화 많이 아시니까, 혹시 뭐 라디오라던가, 뭐 책이라던가 그런 것들은 기억나는 거 없으세요?\n구술자: 그렇죠. 인제 라디오 사오면 저녁에 소위 드라마 같은 거 하고 그러면 우린 라디오가 어떻게 나오는지도 모르고 신기하지. 그냥 거기서 막 우는 소리가 나고 막 그냥 무서운 게 나오면 겁난다 하고 그런 정도로다 순박했지. 라디오가 어떻게 나오는지, 그 성우들이 어떻게 하고 연기자들이 어떻게 하고 이런 걸 모르고.",
    ),
    personPlaceTags: [],
    keywordTags: ["라디오"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC012"],
    relatedItems: [],
  },
  {
    id: "O009",
    itemTitle: "남궁원(1934) 구술 (62–63쪽)",
    dateValue: "1950",
    utterances: seg(
      "면담자: 인제 6.25 때 얘기로 넘어가서, 중학교 3학년 때 전쟁이 일어나잖아요?\n구술자: 아, 그렇죠. 그때 일요일 날인가 그래. 일요일 날 아침인가 집에 이렇게 있는 데 그냥 뭐 쳐들어온다, 뭐 해 가지고 난리가 났고. 인제 라디오가 나오고 막 그냥 그러면서 지금 동두천엘 넘으니 뭐니 하고 그래서 우리, 그때 라디오는 우리 국군이 뭐 반격하고 그러니깐 괜찮다는 둥, 뭐 그렇게 자꾸 위안을 시켰죠. 우리 국민들을. 그러니깐 안심을 했죠.",
    ),
    personPlaceTags: [],
    keywordTags: ["한국전쟁"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC012"],
    relatedItems: [],
  },
  {
    id: "O010",
    itemTitle: "하연남(1927) 구술 (41쪽)",
    dateValue: "1945",
    utterances: seg(
      "면담자: 신당동에서 해방을 맞이하신 거네요. 해방 때 뭐 어디에 계셨고 어떻게 그 해방을 알게 됐는지 기억나세요, 선생님?\n구술자: 그때 라디오를 가지고 있었으니까 라디오 듣고 난리들이 났죠. 지금은 바로 옆인데 그때는 한참 나가야 큰 길이 있어. 큰길에서 만세를 부르고 난리들이 났더라고.",
    ),
    personPlaceTags: [],
    keywordTags: ["해방"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC013"],
    relatedItems: [],
  },
  {
    id: "O011",
    itemTitle: "하연남(1927) 구술 (56쪽)",
    dateValue: "",
    utterances: seg(
      "면담자: 선생님 혹시 일제 시기 때도 라디오 들어 보신 적 있으세요?\n구술자: 그럼요. 우리 집에 라디오도 가지고 있었고 축음기도 가지고 있었고 또 바이올린 가지고 내 동생 바이올린 교습도 하고. 전화도 가지고 있었으니까.",
    ),
    personPlaceTags: [],
    keywordTags: ["일제", "라디오"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC013"],
    relatedItems: [],
  },
  {
    id: "O012",
    itemTitle: "하연남(1927) 구술 (56쪽)",
    dateValue: "",
    utterances: seg(
      "면담자: 일제 때 해방되고 난 다음에 라디오가 달라진 게 있나요?\n구술자: 많이 달라졌죠.\n면담자: 어떤 차이점이 있었나요? 일제 때는 주로 어떤 라디오를 들으셨는데요?\n구술자: 일본말로 다 하잖았어요.\n면담자: 조선어 방송도 있었다고 들었는데\n구술자: 조선어 방송도 했는데 그때는 일본말 시대니까 일본말도 배울 겸 그냥 일본말도 틀었다 한국말도 틀었다 하여간 잊어버렸어요. 그러니까 내가 서울로 올라올 생각도 했을 거예요. 그런 거 안 듣고는 어떻게 서울로 올라올 생각을 했겠어요. 그죠? 그런 거 덕분에. 그러기 때문에 아버지가 축음기를 감추고 라디오도 감추고 이런 것도 당했어요, 내가.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC013"],
    relatedItems: [],
  },
  {
    id: "O013",
    itemTitle: "안건호(1934) 구술 (44쪽)",
    dateValue: "1945~",
    utterances: seg(
      "면담자: 영화, 연극 이외에 만화라든가 뭐 라디오, 음악 같은 거 주로 보고 듣고 좋아하셨던 거 있으세요?\n구술자: 대개, 음악 같은 건 좋아했는데, 요새는 라디오도 많고 아무것 많잖아요. 그때 당시만 해도 뭔 라디오라는 게 거 사실 힘들었어요. 그러구 거기 하꼬(はこ)로 된 거, 손으로 트는 거, 그때 유성기라고 그랬죠. 그거 틀어가지고 그거 저 했는데, 그것도 한 동네 하나나 있지, 집집마다 있는 것도 아니에요. 그래서 남의 집에 가서 그거 한번 구경을 들을라면 상당히 힘들구 그랬더랬어요. 그래서, 그 전에, 요샌 그런지 모르겠어. 그전 애들은 선을 까 가지고 나무에다 걸쳐 가지고 이상하게 저거 해 가지고, 저걸 듣게끔 그런 식으로도 했더라고. 그런 적은 있어요. (웃음) 8.15 해방되구 나서 그것도 했죠. 그전에는 못 했습니다.",
    ),
    personPlaceTags: [],
    keywordTags: ["빨랫줄"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC014"],
    relatedItems: [],
  },
  {
    id: "O014",
    itemTitle: "박행철(1934) 구술 (43쪽)",
    dateValue: "",
    utterances: seg(
      "면담자: 라디오 같은 것들은 좀 들으셨어요?\n구술자: 그렇죠. 라디오는 있는데, 진공관 라디온데, 그것도 들어봐야 조선말 라디오가 거의 없잖아요. 다 일본말 나오고 그러니까 뭐 취미가 그렇게 가질 않아서 애용을 못했어요. 어른들은 저녁 때 되면 뉴스 듣고 하고 뭐 하느라고 라디오를 들었죠.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC015"],
    relatedItems: [],
  },
  {
    id: "O015",
    itemTitle: "박행철(1934) 구술 (96–97쪽)",
    dateValue: "",
    utterances: seg(
      "면담자: 그럼 라디오 같은 것들은 좀 들으셨나요?\n구술자: 라디오는 집에 있었으니까 항상 들었죠. 라디오는 저녁에 뭐 여기 연속극 같이 오락프로는 없었지만 그래도 뉴스라든가 뭐 이런 것들은 가끔 듣고 그랬죠.\n면담자: 그 남한지역에서는 50년대 중반에 라디오 드라마 같은 것들이 많이 유행을 하잖아요. 근데 북한지역에서도 그런 어떤 프로그램들이 있었나요? 그런 건 없었고 뉴스만 있었나요?\n구술자: 거의 없었던 것 같아. 그러니까 걔네들 그 드라마라는 게 소위 사상적으로 뭐 공장 노동자 얘기, 뭐 여기 얘기하자면 그 새마을, 그런 그 비유된 {그런 류의} 그런 정도지. 크게 무슨 빛나게 아주 인기작이라던가 그런 게 없었어요.",
    ),
    personPlaceTags: [],
    keywordTags: ["북한", "장연"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC015"],
    relatedItems: [],
  },
  {
    id: "O016",
    itemTitle: "최하원(1937) 구술 (39쪽)",
    dateValue: "1945",
    utterances: seg(
      "구술자: 거기에 그 일본 두 집인가 세 집이 있는데 전부 식구들이 이렇게 마당에 모여가지고 무릎을 꿇고 그 라디오 방송을 듣는 거야. 그리고 나중엔 뭐 거기다 대고 절을 하고 뭐, 저희들끼리 막 울고 뭐 그러는 걸로 지금 기억을 하는데.\n면담자: 아. 그것을 직접 보셨어요? 지나가면서?\n구술자: 본거야. 응, 응. 그런 걸 봤어. 그 날인지 언젠지 모르겠지만 아버지가 나를 데리고 서울역으로 가 가지고 이제 대한독립만센가 뭔가 막 부르고 인제, 그때 왜 서울역에 군중들이 드렇게 모였는지 그건 모르겠어. 근데 서울역을 그때 내가 아버지 손잡고 손에 끌려가지고 거기 가 가지고 만세들 부르는 걸 구경하고 그런 적은 있어. 기억이 나.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC016"],
    relatedItems: [],
  },
  {
    id: "O017",
    itemTitle: "최하원(1937) 구술 (47쪽)",
    dateValue: "",
    utterances: seg(
      "구술자: 내가 국민학교 때 라디오 들으면서 좋았던 게 <똘똘이의 모험> 그 때거든? 그러니깐 활성화되지는 않았을 때죠. 그때.\n면담자: 오승룡 선생님 인터뷰때 해방되고 나서 역사 강의 같은 것도 많이 라디오에서 했다고 말씀을 하시더라고요. 혹시 들어보신 적 없나요?\n구술자: 몰라. 그런 것은 어렸을 때니까 내가 관심이 없없을 거지만. 어쨌든 <똘똘이의 모험> 뭐 그런 것은 열심히 들었고. 그 다음에 조남사 씨의 연속극 <청실홍실>, <산넘어 바다 건너> 그런 것들이 굉장히 장안의 화제가 되고 그랬죠.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC016"],
    relatedItems: [],
  },
  {
    id: "O018",
    itemTitle: "김지헌(1930) 구술 (68쪽)",
    dateValue: "1945~1948",
    utterances: seg(
      "면담자: 미군정 들어오고 나서 가장 달라진 점이 뭐가 있나요, 선생님? 예를 들면 극장에 영화들도 많이 달라졌고...\n구술자: 외화가 쏟아져 들어왔고.\n면담자: 라디오나 이런 데서 드라마 같은 것도 많이 했다고 들었거든요?\n구술자: 그렇지. 그때는 장민호 씨가 소설 낭독하고. 아침마다 낭독도 하고. 그땐 텔레비전이 없을 때니가. 유일하게 라디오드라마. 한운사 씨, 조남사 씨나 이런 사람들. 다 친한 사람들이지.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC017"],
    relatedItems: [],
  },
  {
    id: "O019",
    itemTitle: "황의순(1935) 구술 (49쪽)",
    dateValue: "1936?/1942?",
    utterances: seg(
      "구술자: 공작시간 같은때 뭐 만들고 하던 기억은 있는데, 학예회라는 걸 가끔 하잖아. 그런 거 한 번씩 있었고. 그 사람들이 우리 시대에는 일본말 치중해서 가르치고 일본식 교육 하는 데 총력을 했기 때문에. 그리고 라디오 다이소(ラジオ体操)라 그래가지고 라디오에 맞춰서 체육하는 거, 그거를 상당히 중점적으로 가르치고 그랬지. 초등학생들에게는.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    notes: "라디오 다이소는 국민보건체조를 가리킨다.",
    sourceRef: SOURCES["SRC018"],
    relatedItems: [],
  },
  {
    id: "O020",
    itemTitle: "황의순(1935) 구술 (257쪽)",
    dateValue: "1978~",
    utterances: seg(
      "면담자: 선생님 <미국의 소리> 서울 지국장도?\n구술자: 그게 78년부터 했지? 내가.\n면담자: 네. 78년.\n구술자: 78년부터 쭉 했지. 한 십 몇년 했을 거야.",
    ),
    personPlaceTags: [],
    keywordTags: ["미대사관", "미국의소리"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC018"],
    relatedItems: [],
  },
  {
    id: "O021",
    itemTitle: "황의순(1935) 구술 (257–258쪽)",
    dateValue: "1978~",
    utterances: seg(
      "면담자: <보이스 오브 아메리카> 같은 경우에는 어느 정도 인력을 계속 미국으로 보내야 했던 건가요?\n구술자: 여기서 내가 특별한 기사 꺼리가 있으면 그냥 해서 보내는 거야. 그러면 버블이라는 데가 있어. 여기서 전화에다 대고 그냥 목소리로 방송을 하면 24시간 거기서 레코딩이 되니까, 거기서 뜯어갖고 그거 쓰는 거야, 뉴스를.\n면담자: 버블.\n구술자: 버블시스템이라고 있어. 전화에다 대고 하는 거니까. 어차피 그림이 필요 없잖아. <미국의 소리 방송은>. 숏 웨이브 단파방송이니까. 그러면 버블에다 대고 \"디스 이즈 보이스 오브 어메리카 서울 콜링\" 하면 녹음이 시작 되는 거야. 그러면 아침에 와서 다 뜯어보는 거지 그 사람들이. '서울에서 이런 기사가 들어왔는데 이거 쓸까?' 이렇게 하는 거지.",
    ),
    personPlaceTags: [],
    keywordTags: ["미대사관", "미국의소리"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC018"],
    relatedItems: [],
  },
  {
    id: "O022",
    itemTitle: "강범구(1924) 구술 (143쪽)",
    dateValue: "1962",
    utterances: seg(
      "면담자: 감독님 <검은 꽃잎이 질 때> 그 라디오 드라마 방송 할 때요. 그때 라디오 프로 들으신 적 있으세요?\n구술자: 있는데 다 듣진 못했지 나는.\n면담자: 예 그때부터 되게 인기가 많았잖아요. {그렇지 그럼} 라디오 드라마 할 때부터, 왜 인기요인이 뭐였을까요?\n구술자: 아 그때는 인제 돈 많은 사람들은 극장에 가서 영화들을 보는데, 연극이나 영화들을 보는데, 고때만 하더라도 연극이 조금 식어갈 때야. 영화가 조금 이래 올라갈 땐데, 영화 못 보는 사람들은 이 라디오 드라마는 돈 없이 들을 수가 있으니까 가다가 그냥 라디오 있으면은 서서들 길거리에서도 듣고 인제 그랬거든. 그니까 어떤 저 레코드상 같은 데서는 일부러 고 시간에 또 틀어 놔요. 그래 길거리에서 들으라고. 뭐 노래 같은 것도 많이 틀고 그러지만, 그래 충무로 입구에 거기에 레코드 파는 가게가 많았었다고. 그래 거기에 딱 지나가면 이 집, 저 집이서 유행되는 레코드하고 레디오 드라마를 많이 들었지. 그래서 레디오 드라마들을 많이들 저거 하고, 또 레디오 드라마 그때 하여튼 돈 없이 듣는 거로서는 그게 제일 오락 중에 하나 그 저거니까 네.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC019"],
    relatedItems: [],
  },
  {
    id: "O023",
    itemTitle: "이달형(1929) 구술 (73쪽)",
    dateValue: "1960s",
    utterances: seg(
      "구술자: 나는 그 당시에 할애요청을 받아 가지고 기꺼이 가겠다고 그랬어요. 그 프로그램이 아까도 얘기했지만 <농촌방송토론클럽>이라고 하는 좌담 프로그램입니다. 그 좌담 프로그램은 '농촌에 농사를 어떻게 과학적으로 짓느냐' 그런 것이 위주가 돼 가지고 좌담을 하는 건데. 주로 기술자도. 그것은 이제 농림부 산하에 농촌진흥원에서 전문가가 나와 가지고 이쪽 사람들하고 대담을 하는 겁니다, 농촌 대표자하고. 이제 그것을 총괄하는 책임자 역할을, 내가 PD 역할을 했어요. 그걸 쭉 1주일 한 번씩 나가는 건데. 우리 직원들이 7, 8명 있었습니다. 일종에 AD 역할 하는 사람들이. 그래 가지고 1년 정도? 1년도 아마 못 됐을 거예요.",
    ),
    personPlaceTags: [],
    keywordTags: ["서울중앙방송국"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC020"],
    relatedItems: [],
  },
  {
    id: "O024",
    itemTitle: "김동호(1937) 구술 (65쪽)",
    dateValue: "1960s",
    utterances: seg(
      "구술자: 1927년에 KBS 라디오가 출범을 하고 1957년에 부산에서 처음으로 민영방송 MBC지요, 생기고 그러면서 방송이 보급되기 시작을 했어요. 그러나 전국에 난시청 지역이 워낙 많았기 때문에 전국에 유선방송망을 깔고 라디오와 스피커를 보내주는 운동, 그런 운동이 함께 전개가 됐죠. 동시에 KBS의 라디오 망을 전국적으로 확충하고 난시청 지역을 없애기 위해서 중계소나 송신소를 곳곳에 건설해서 많은 국민들이 라디오를 들을 수 있도록 하는 데 역점을 뒀고.",
    ),
    personPlaceTags: [],
    keywordTags: ["5.16 군사정부"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC021"],
    relatedItems: [],
  },
  {
    id: "O025",
    itemTitle: "김동호(1937) 구술 (74–75쪽)",
    dateValue: "1960s",
    utterances: seg(
      "구술자: 특히 5.16 직후에 가장 먼저 생긴 것이 61년 12월 24일 날, 크리스마스 이브에 남산에 있던, 그 후에 영화진흥공사 사옥으로 바뀌었지만, 그 전에 KBS TV국이었는데, 남산에 있는 KBS TV국에서 텔레비전 방송이 처음 시작이 됐죠. 64년에 민방이 또 계속 뒤를 이어서 나왔고, 61년부터 KBS TV가 생겼기 때문에 KBS 라디오나 TV가 정부시책과 업적을 알리는 데 주 역할을 많이 했죠.",
    ),
    personPlaceTags: [],
    keywordTags: ["5.16 군사정부"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC021"],
    relatedItems: [],
  },
  {
    id: "O026",
    itemTitle: "송길한(1940) 구술 (97쪽)",
    dateValue: "1977",
    utterances: seg(
      "면담자: 77년도에 특이하게도 애니메이션 각본 작업을 하셨더라고요.\n구술자: 음.\n면담자: <태권동자 마루치 아라치>(임정규, 1977)\n구술자: 어떤 개인 제작자가 해서. 라디오 드라마로서 그때 당시 청소년들을 대단히 응? 연속드라마로서 히트를 친 거 아니에요? 그걸 영화로 한다 이것이죠. 시나리오를 써 달라 이거예요. 누가 써 논 시나리오가 있었어요. 그런데 그것도 아니고 뭐 라디오 드라마에 있는 드라마로서의 그 대본도 시원치 않고 그러니까 특별히 부탁을 해서 써줬죠. 근데 그것이 아마 그때는 부모님들하고 애들하고 손잡고 막 들어가고 그러는 바람에 거의 폐관이 되다시피 한 중앙극장에 느닷없는 풍이 일었죠, 그게. 그때 당시로 한 30여 만, 40만 가까이 들었으니까 빅히트를 친 거예요 그게.",
    ),
    personPlaceTags: [],
    keywordTags: ["<태권동자 마루치 아라치>"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC022"],
    relatedItems: [],
  },
  {
    id: "O029",
    itemTitle: "구흥서(1938) 구술 (50쪽)",
    dateValue: "1979",
    utterances: seg(
      "구술자: 당시 저희 집이 북아현3동에 있었어요. 아침이면 라디오 테이프를 꽂고 새마을 노래를 틀었어요. 집 옥상에 정식으로 스피커를 달아서 5시 50분이면 정확하게 제가 새마을 노래를 틀었습니다. 우선 저희 집 아이들부터 시작했어요. 그러니까 동네 아이들이 한 놈, 두 놈, 자꾸 모여드는 거예요.",
    ),
    personPlaceTags: [],
    keywordTags: [],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC025"],
    relatedItems: [],
  },
  {
    id: "O030",
    itemTitle: "이수복(1939) 구술 (129–130쪽)",
    dateValue: "1974",
    utterances: seg(
      "구술자: 1974년도에 첫 시운전을 할 때 긴장했죠. 혹시 차량 운행으로 인한 진동이 이 건물에 영향을 미칠까 하고요. 저는 잘 알죠. 동아일보 건물 기둥과 우리 지하철 사이에는 채 2m도 떨어져 있지 않다는 것을요.\n면담자: 정말 긴장하셨겠네요.\n구술자: 당시 그 건물에 동아방송국이 있었어요. DBS였죠. 그때 라디오 심야방송이 있었거든요. 제가 오디오를 좋아해요. 그런데 턴테이블에 조그마한 진동이 있어도 어떻게 됩니까? 바늘이 튀죠. 조그마한 진동에도 그게 흔들린다고요. LP판에 반들이 진동으로 흔들리면 '찌-익' 소리가 나잖아요. 제가 그걸 제일 걱정했어요. 혹시 지하철 진동으로 인해 심야방송을 할 때 턴테이블에 바늘이 튀면 어떡하나 하고요. 그때 동이일보 이언진 부사장이라고 있었는데, \"지하철 시운전을 하는데 혹시 이러한 문제가 있을지도 모르니 확인 차원에서 음악방송이 아니더라도 턴테이블을 돌려봐 달라.\"고 부탁했어요. 만약에 영향이 있다면 우리는 선로 밑에 뭘 더 깔고 대책을 강구해야 하거든요. 가령 방진패드를 깔든가 해야죠.\n면담자: 그때가 개통식이 있던 1974년 광복절 이전이었죠?\n구술자: 맞아요. 개통식에 앞서 봄에 시운전을 시작했죠. 그랬더니 1주일 후에 동아일보 측에서 연락이 왔어요. 괜찮다고요. '아, 살았다!' 싶었죠. 잘 통과해서 다행이었죠.",
    ),
    personPlaceTags: [],
    keywordTags: ["지하철 시운전", "동아일보"],
    hasDiscrepancy: false,
    sourceRef: SOURCES["SRC026"],
    relatedItems: [],
  },
];
